######### API Users ########

### Post - menambahkan user baru beserta dengan profilnya.
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "first_name": "Kepin",
    "last_name": "Yohanes",
    "email": "Kepin@gmail.com",
    "password": "12345"
}

### GET - menampilkan daftar users.
GET http://localhost:3000/api/v1/users

### UPDATE - USERS
PUT http://localhost:3000/api/v1/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkRld2FuZ2dhIiwibGFzdF9uYW1lIjoiTmFuZGEiLCJlbWFpbCI6ImRld2FuZ2dhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQzOTU2NTR9.f9dcAlLaibk86s6kUYywTVe1kzbDfuI-4hDzuZeNeqc

{
    "first_name": "Dewangga",
    "last_name": "Nanda",
    "email": "Dewangga@gmail.com",
    "address": "Surabaya",
    "occupation": "Mahasiswa"   
}

### UPDATE - Avatar
PUT http://localhost:3000/api/v1/users/2/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkRld2FuZ2dhIiwibGFzdF9uYW1lIjoiTmFuZGEiLCJlbWFpbCI6ImRld2FuZ2dhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQzOTU2NTR9.f9dcAlLaibk86s6kUYywTVe1kzbDfuI-4hDzuZeNeqc

{
    "imageUrl": "https://ik.imagekit.io/dewangga/1714399894213_GlnkPZdNV.png"
}

############################


######### API Auth #########

### POST - LOGIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "first_name": "Dewangga",
    "last_name": "Nanda",
    "email": "Dewangga@gmail.com"
}

### GET - Authenticate
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkRld2FuZ2dhIiwibGFzdF9uYW1lIjoiTmFuZGEiLCJlbWFpbCI6ImRld2FuZ2dhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQzOTU2NTR9.f9dcAlLaibk86s6kUYywTVe1kzbDfuI-4hDzuZeNeqc

############################